config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases do
    member do
      get 'new_base_info'
    end
  end

  resources :users do
    get 'applicants', on: :collection
    collection {post :import}
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'show2'
      get 'edit2'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      patch 'basic_info'
      get 'edit_overwork_notice'
      patch 'update_overwork_notice'
      get '/attendances/edit_one_month_apply'
      patch 'attendances/update_one_month_apply'
      patch 'attendances/request_one_month_application'
      get '/attendances/edit_attendance_apply'
      patch '/attendances/update_attendance_apply'
      get '/attendances/edit_attendance_log'
    end

    resources :attendances do
      collection {post :import}
      member do
        patch 'update'
        get 'edit_overwork_request'
        patch 'update_overwork_request'
      end
    end
  end
  
  resources :attendance_change_approval_log, only: :index
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                         :integer          not null, primary key
#  name                       :string           not null
#  email                      :string           not null
#  password_digest            :string
#  remember_digest            :string
#  admin                      :boolean          default(FALSE), not null
#  department                 :string
#  basic_time                 :datetime         default(Fri, 18 Feb 2022 08:00:00 JST +09:00), not null
#  work_time                  :datetime         default(Fri, 18 Feb 2022 07:30:00 JST +09:00), not null
#  superior                   :boolean          default(FALSE), not null
#  designated_work_start_time :datetime         default(Fri, 18 Feb 2022 09:00:00 JST +09:00), not null
#  designated_work_end_time   :datetime         default(Fri, 18 Feb 2022 18:00:00 JST +09:00), not null
#  finish_time                :datetime
#  affiliation                :string
#  employee_number            :integer
#  uid                        :string
#  title                      :string
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  
  has_many :attendances, dependent: :destroy
  has_many :attendance_change_approval_logs, dependent: :destroy
  #has_many :bases, class_name: "Base", dependent: :destroy
  
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 100},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: true
                    
  validates :affiliation, length: { in: 3..30 }, allow_blank: true
  validates :employee_number, length: {maximum: 4}, uniqueness: true, allow_blank: true
  validates :uid, uniqueness: true, allow_blank: true
  validates :basic_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  validates :work_time, presence: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true               
 
 #def self.search(search)
  #return User.all unless search
   #User.where(['name LIKE ?', "%#{search}%"])
 #end

 def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
 end
 
 
 def User.new_token
  SecureRandom.urlsafe_base64
 end
 
 def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
 end
 
 
 def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
 end

 def forget
  update_attribute(:remember_digest, nil)
 end
 
 def working_user
  if User.find(id: working_user).attendances.(worked_on: Date.today).started_at.present? && finished_at.nil?
   return @working_user.employee_number, @working_user.name
  end
 end
 
 
 def self.import(file)
  CSV.foreach(file.path, headers: true, encoding: 'Shift_JIS:UTF-8') do |row|
    user = find_by(id: row["id"]) || new
    user.attributes = row.to_hash.slice(*updatable_attributes)
    user.save
  end
 end
 
 def self.updatable_attributes
  ["name", "email", "affiliation", "employee_number", "uid", "basic_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
 end
 

 



end

app/controllers/users_controller.rb
require 'csv'

class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :show2, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :edit_attendance_log]
  #before_action :correct_user, only: [:edit, :update]
  before_action :admin_or_correct_user, only: [:show, :edit, :index, :update, :edit_one_month, :update_one_month, :edit_attendance_log]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: [:show, :show2]
  #before_action :superior_user, only: [:show2]

  def index
    #binding.pry
    #if params[:search] == ""
    #@users = User.where(params[:search])
    #end
  
    @users =  User.where.not(id: 1)
    
    @users = @users.where('name LIKE?', "%#{params[:search]}%") if params[:search].present?
    #respond_to do |format|
        #format.html
        #format.csv do |csv|
         #send_users_csv(@users)
        #end
    #end
  end
  
  def search
    if params[:search] != ""
     @users = User.search(params[:search])
    else
     @users = User.all
    end
    binding.pry
  end
  
  #def send_users_csv(users)
    #bom = "\uFEFF"
    #csv_data = CSV.generate(bom) do |csv|
      #header = %w(ユーザー名 メールアドレス 所属 社員番号 カードID 基本勤務時間  指定勤務開始時間 指定勤務終了時間 上長フラグ 管理者フラグ パスワード)
      #header = %w(name email affiliation employee_number uid designated_work_start_time designated_work_end_time superior admin password)
      #csv << header
      #users.each do |user|
        #values = [user.name, user.email, user.affiliation, user.employee_number, user.uid, user&.designated_work_start_time&.strftime('%H:%M'), user&.designated_work_end_time&.strftime('%H:%M'), user.superior, user.admin, user.password]
        #csv << values
      #end
      
    #end
    #send_data(csv_data, filename: "ユーザー情報一覧.csv")
  #end
  
  #def import
    #if params[:csv_file].blank?
      #redirect_to(user_url)
    #else
      #num = Admin::User.import(params[:csv_file])
      #redirect_to(users_url, notice: "#{num.to_s}の件のユーザー情報を追加・更新しました")
    #end
  #end
  
  def import
    User.import(params[:file])
    flash[:success] = "新規ユーザーを追加しました。"
    redirect_to users_url
  end
  
  def applicants
   @working_in_users = User.includes(:attendances)
   unless current_user.admin?
    flash[:danger] = "閲覧権限がありません。"
    redirect_to root_path
   end
  end

  def show
    #binding.pry
   @user = User.find(params[:id])
   if current_user.admin?
     flash[:danger] = "管理者は閲覧権限がありません。"
     redirect_to root_url
   end
   #@attendance = @user.attendances.find_by(worked_on: Date.today)
   #if @user == current_user || current_user.admin?
    #@first_day = Date.current.beginning_of_month
   #@last_day = @first_day.end_of_month(@first_day..@last_day).each do |day| unless @user.attendances.any? {|attendance| attendance.worked_on == day}
    #record = @user.attendances.build(worked_on: day)
    #record.save
     #end
    #end
   #@dates =user.attendances_month_date
   user = User.find(params[:id])
    @first_day = params[:date]&.to_date || Date.current.beginning_of_month
    @last_day = @first_day.end_of_month
    @attendances = user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
    @one_month_apply_count = Attendance.where(one_month_superior_id: current_user.id).where(one_month_status: 1).count
    #binding.pry
    @apply_attendances_count = Attendance.where.not(renewed_finished_at: nil).where(superior_choice_id: current_user.id).where(attendance_state: 1).count
    #binding.pry
    @overwork_time_count =  Attendance.where.not(contents: nil).where(select_superior_id: current_user.id).where(superior_state: 1).count
    #binding.pry
    @worked_sum = @attendances.where.not(started_at: nil).count
    @superiors = User.where(superior: true).where.not(id: current_user)
    @attendance = Attendance.find(params[:id])
    @over_apply = User.where(superior: true).where.not(id: current_user)
    @attendance_apply = User.where(superior: true).where.not(id: current_user)
    @beginning_of_month_attendance = user.attendances.find_by(worked_on: @first_day)
    @change_application = user.attendances.find_by(worked_on: @first_day)
   #binding.pry
   #else
     #redirect_to root_url
   #end
   respond_to do |format|
        format.html
        format.csv do |csv|
         send_attendances_csv(@attendances)
        end
    end
  end
  
  
   def send_attendances_csv(attendances)
    bom = "\uFEFF"
    csv_data = CSV.generate(bom) do |csv|
      #header = %w(day.worked_on attendance.worked_on.wday started_at finished_at)
      header = %w(日付 曜日 出勤時間  退勤時間)
      csv << header
      @attendances.each do |attendance|
        #binding.pry
        if attendance.started_at.present? && attendance.finished_at.present? && attendance.attendance_state == 1 
            values = [l(attendance.worked_on, format: :short), $days_of_the_week[attendance.worked_on.wday], attendance&.started_at&.strftime('%H:%M'), attendance&.finished_at&.strftime('%H:%M')]
            csv << values
        else if attendance.started_at.present? && attendance.finished_at.present? && attendance.attendance_state == 2
            values = [l(attendance.worked_on, format: :short), $days_of_the_week[attendance.worked_on.wday], attendance&.started_at&.strftime('%H:%M'), attendance&.finished_at&.strftime('%H:%M')]
            csv << values
        else
            values = [l(attendance.worked_on, format: :short), $days_of_the_week[attendance.worked_on.wday]]
            csv << values
        end
        end
      end
    end
    send_data(csv_data, filename: "勤務実績.csv")
   end
   #@overtime = Attendance.where(indicator_reply: "申請中", indicator_check: @user.name).count
  
  def show2
    #@user = User.where.not(id: current_user.id)
    user = User.find(params[:id])
    @first_day = params[:date]&.to_date&.beginning_of_month || Date.current.beginning_of_month
    @last_day = @first_day.end_of_month
    #@attendances = user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
    @worked_sum = @attendances.where.not(started_at: nil).count
    @beginning_of_month_attendance = user.attendances.find_by(worked_on: @first_day)
   #@overtime = Attendance.where(indicator_reply: "申請中", indicator_check: @user.name).count
    @attendances = user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
    @one_month_apply_count = Attendance.where(one_month_superior_id: current_user.id).where(one_month_status: 1).count
    #binding.pry
    @apply_attendances_count = Attendance.where.not(renewed_finished_at: nil).where(superior_choice_id: current_user.id).where(attendance_state: 1).count
    #binding.pry
    @overwork_time_count =  Attendance.where.not(contents: nil).where(select_superior_id: current_user.id).where(superior_state: 1).count
    #binding.pry
    @superiors = User.where(superior: true).where.not(id: current_user)
    @attendance = Attendance.find(params[:id])
    @over_apply = User.where(superior: true).where.not(id: current_user)
    @attendance_apply = User.where(superior: true).where.not(id: current_user)
    @change_application = user.attendances.find_by(worked_on: @first_day)
  end
  
  def new
    if logged_in? && !current_user.admin?
     flash[:warning] = "すでにログインしています。"
     redirect_to current_user
    end
     @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      #(Date.parse('2021-01-01')..Date.parse('2022-12-31')).select{|d| d.day == 1}.each do |day|
        #first_day = day
        #first_day = Date.current.beginning_of_month
        #last_day = first_day.end_of_month
        #one_month = [*first_day..last_day]
        #one_month.each {|day| @user.attendances.create!(worked_on: day)}
      #end
      flash[:success] = 'ユーザー新規登録に成功しました。'
      log_in @user
      redirect_to @user
      # 保存に成功した場合は、ここに記述した処理が実行されます。
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
    #if params[:password] != params[:password_confirmation]
      #flash[:danger] = "更新に失敗しました。"
    #end
    if current_user.admin?
      flash[:danger] = "閲覧権限がありません。"
      redirect_to root_path
    end
  end
  
  #def edit2
    #@user = User.find(params[:id])
  #end
  
  
  def update
    #binding.pry
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
       flash[:success] = "ユーザー情報を更新しました。"
      if current_user.admin?
       redirect_to users_path
      else
       redirect_to user_path(@user)
      end
    else
      if current_user.admin?
       flash[:danger] = "登録内容に不備がある為、登録に失敗しました。"
       redirect_to users_path
      else
       render :edit
      end
    end
  end
  
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  

  def update_basic_info
   if @user.update_attributes(basic_info_params)
     flash[:success] = "#{@user.name}の基本情報を更新しました。"
   else
     flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
   end
     redirect_to users_url
  end
  
  def edit_overwork_notice
    @users = User.where.not(id: 1).where.not(id: current_user.id).eager_load(:attendances).where.not(attendances: {contents: nil}).where(attendances: {select_superior_id: current_user.id}).where(attendances: {superior_state: 1})
    #binding.pry
    @user = User.find(params[:id])
    @attendances = @user.attendances
    @attendance = Attendance.find(params[:id])
  end
  
  def update_overwork_notice
     #@user = User.where(id: 7)
     #@attendance = Attendance.where(id: 4..13)
      ActiveRecord::Base.transaction do # トランザクションを開始します。
        update_overwork_notice_params.each do |id, item|
          if ActiveRecord::Type::Boolean.new.cast(item[:modification]) && item[:superior_state] == "2"
            attendance = Attendance.find(id)

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    #binding.pry
    format("%.2f", ((time.hour * 60.0) + time.min) / 60.0)
  end
  
  def designated_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60)
  end
  
  def format_hour
    format("%.2f", (user.designated_work_start_time.to_i))
  end
  
  
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :department, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :department, class: "form-control" %>

            <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
 </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "⇦", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        &emsp;<%= l(@first_day, format: :middle) %> 時間管理表&emsp;
        <%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
      </td>
      <td>
        指定勤務開始時間: <%= designated_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間: <%= designated_info(@user.designated_work_end_time) %>
      </td>
      <td colspan="3">基本時間: <%= format_basic_info(@user.basic_time) %></td>
      <td>月初日: <%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属: <%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>名前: <%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.employee_number %></td>
      <td>出勤日数: <%= @worked_sum %>日</td>
      <td>月末日: <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div>
  <% if current_user.superior? %>
   <nav>
     <ul class="menu-notice">
       <li>
         <% if @one_month_apply_count != 0 %>
           <%= link_to "[ 所属長承認申請のお知らせ ]", attendances_edit_one_month_apply_user_path(@user), class: "text-danger", remote: true %>
           <span style="color: red; border: 3px solid #F00;">&emsp;<%= @one_month_apply_count %>件の通知があります&emsp;</span>
         <% else if @one_month_apply_count == 0 %>
           <%= "[ 所属長承認申請のお知らせ ]" %>
          <% end %>
         <% end %>
        </li><br>
       <li>
         <% if @apply_attendances_count != 0 %>
           <%= link_to "[ 勤怠変更申請のお知らせ ]", attendances_edit_attendance_apply_user_path(@user), class: "text-danger", remote: true %>
           <span style="color: red; border: 3px solid #F00;">&emsp;<%= @apply_attendances_count %>件の通知があります&emsp;</span>
         <% else if @apply_attendances_count == 0 %>
           <%= "[ 勤怠変更申請のお知らせ ]" %>
          <% end %>
         <% end %>
        </li><br>
       <li>
        <% if @overwork_time_count != 0 %>
         <%= link_to "[ 残業申請のお知らせ ]", edit_overwork_notice_user_path(@user), class: "text-danger", remote: true %>
         <span style="color: red; border: 3px solid #F00;">&emsp;<%= @overwork_time_count %>件の通知があります&emsp;</span>
        <% else if @overwork_time_count == 0 %>
          <%= "[ 残業申請のお知らせ ]" %>
         <% end %>
        <% end %>
       </li><br>
     </ul>
   </nav>
  <% end %>
</div>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "勤怠修正ログ(承認済)", attendance_change_approval_log_index_path, class: "btn btn-default btn-primary" %>
</div>

<div class="csv_holder">
  <%= form_tag "import_user_path", method: :post, multipart: true do |f| %>
    <div class="search_item">
      <%= link_to 'CSVを出力', user_path(@user, date: @first_day.strftime("%F"), format: :csv), class: "btn btn-primary" %>
    </div>
  <% end %>
</div><br>
  


<div>
  <table class="table table-striped table-bordered table-condensed" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="2"></th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">実績</th>
        <th colspan="5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>残業申請</th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>

    <tbody>
      <%# binding.pry %>
      <% @attendances.each do |attendance| %>
      <%# binding.pry %>
        <tr>
          <td><%= link_to "残業申請", edit_overwork_request_user_attendance_path(@user, attendance), remote: true, class: "btn btn-primary" %></td>
          <td><%= l(attendance.worked_on, format: :short) %></td>
          <td>
            <% if attendance.worked_on.wday == 6 %>
             <font color="blue">土</font>
            <% elsif attendance.worked_on.wday == 0 %>
             <font color = "red">日</font>
            <% else %>
             <%= $days_of_the_week[attendance.worked_on.wday] %>
            <% end %>
          </td>
          <td>
            <% if attendance.started_at.present? && attendance.renewed_started_at.blank? %>
              <%= attendance.started_at.hour %>
            <% else if attendance.renewed_started_at.present? %>
              <%= attendance.renewed_started_at.hour %>
             <% end %>
             <% end %>
          </td>
          <td>
            <% if attendance.started_at.present? && attendance.renewed_started_at.blank? %>
              <%= format_min(attendance.started_at) %>
            <% else if attendance.renewed_started_at.present? %>
              <%= format_min(attendance.renewed_started_at) %>
             <% end %>
             <% end %>
          </td>
          <td>
            <% if attendance.worked_on == Date.current && attendance.started_at.nil? %>
             <%= link_to "出勤", user_attendance_path(@user, attendance), method: :patch, class: "btn btn-primary btn-block btn-attendance" %>
            <% end %>
          </td>
          <td>
            <% if attendance.finished_at.present? && attendance.renewed_finished_at.blank? %>
             <%= attendance.finished_at.hour %>
            <% else if attendance.renewed_finished_at.present? %>
             <%= attendance.renewed_finished_at.hour %>
             <% end %>
             <% end %>
          </td>
          <td>
            <% if attendance.finished_at.present? && attendance.renewed_finished_at.blank? %>
             <%= format_min(attendance.finished_at) %>
            <% else if attendance.renewed_finished_at.present? %>
             <%= format_min(attendance.renewed_finished_at) %>
             <% end %>
             <% end %>
          </td>
          <td>
            <% if attendance.worked_on == Date.current && attendance.started_at.present? && attendance.finished_at.nil? %>
             <%= link_to "退勤", user_attendance_path(@user, attendance), method: :patch, class: "btn btn-primary btn-block btn-attendance" %>
            <% end %>
          </td>
          <td>
            <% if attendance.started_at.present? && attendance.finished_at.present? && attendance.renewed_started_at.blank? && attendance.renewed_finished_at.blank? %>
             <%= str_times = working_times(attendance.started_at, attendance.finished_at, attendance) %>
             <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
            <% if attendance.renewed_finished_at.present? %>
             <%= str_times = renew_working_times(attendance.renewed_started_at, attendance.renewed_finished_at, attendance) %>
             <% @renewed_working_times = @renewed_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= attendance.description %></td>
          <td>
            <% if attendance.finish_time.present? %>
              <%= attendance.finish_time.hour %>
            <% end %>
          </td>
          <td>
            <% if attendance.finish_time.present? %>
             <%= format_min(attendance.finish_time) %>
            <% end %>
          </td>
          <td>
            <% if attendance.finish_time.present? && @user.designated_work_end_time.present? %>
             <%= overtime_info(@user.designated_work_end_time, attendance.finish_time, attendance) %>
            <% end %>
          </td>
          <td>
            <% if attendance.contents.present? %>
              <%= attendance.contents %>
            <% end %>
          </td>
          <td>
            <% if attendance.select_superior_id != nil && attendance.superior_state == 1 %>
              <h5><span class= "over"><%= attendance.select_superior&.name %></span>に残業申請中</h5>
            <% end %>
            <% if attendance.superior_state == 2 %>
             <h5 style = "color :blue">残業申請承認済み</h5>
            <% end %>
            <% if attendance.superior_state == 3 %>
             <h5 style = "color :red">残業申請否認</h5>
            <% end %>
            
            <% if attendance.superior_choice_id != nil && attendance.attendance_state == 1 %>
              <h5><span class= "change"><%= attendance.superior_choice&.name %></span>に勤怠変更申請中</h5>
            <% end %>
            
            <% if attendance.attendance_state == 2 %>
             <h5 style = "color :blue">勤怠変更承認済み</h5>
            <% end %>
            
            <% if attendance.attendance_state == 3 %>
              <h5 style = "color :red">勤怠変更否認</h5>
            <% end %>
            
            
            <% if attendance.attendance_state == 4 && attendance.previous_attendance_state == 2 %>
            <%# binding.pry %>
              <h5 style = "color :blue">勤怠変更承認済み</h5>
            <% end %>
            
            <% if attendance.attendance_state == 4 && attendance.previous_attendance_state == 3 %>
            <%# binding.pry %>
              <h5 style = "color :red">勤怠変更否認</h5>
            <% end %>
            
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <!--rowspan:縦結合、colspan：横結合-->
      <tr>
        <td>累計日数</td>
        <td colspan="2">総合勤務時間</td>
        <td colspan="6">累計在社時間</td>
        <td></td>
        <td colspan="5"></td>
        <td></td>
      </tr>
      <tr>
        <td><%= @attendances.count %></td>
        <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="6">
          <%= format("%.2f", @total_working_times.to_f) %>
        </td>
        <td></td>
        <td colspan="5"></td>
        <td>
          <% if @beginning_of_month_attendance.one_month_superior_status == '申請中' && @beginning_of_month_attendance.one_month_status == 1 %>
            <span class= "leader"><%= @beginning_of_month_attendance.one_month_superior&.name %></span>に所属長承認申請中
          <% else if @beginning_of_month_attendance.one_month_status == nil %>
            <h5>所属長承認 未申請</h5>
          <% end %>
          <% end %>
          
          <% if @beginning_of_month_attendance.one_month_status == 2 %>
            <h5 style = "color :blue">所属長承認 承認済み</h5>
          <% end %>
          <% if @beginning_of_month_attendance.one_month_status == 3 %>
            <h5 style = "color: red">所属長承認 否認</h5>
          <% end %>
          <% if @beginning_of_month_attendance.one_month_status == 4 %>
            <h5>所属長承認 未申請</h5>
          <% end %>
          
          <%= form_with(model: @user, url: attendances_request_one_month_application_user_path(@user, date: @first_day), local: true, method: :patch) do |f| %>
              <%= f.collection_select :one_month_superior_id, @superiors, :id, :name, :prompt => "送信先を選択" %>
              <%= f.submit "申請", remote: true, class: "btn btn-block btn-primary" %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>
</div>

<div id="edit-overwork-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-overwork-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-one-month-apply" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-attendance-apply" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>