config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases do
    member do
      get 'new_base_info'
    end
  end

  resources :users do
    get 'applicants', on: :collection
    collection {post :import}
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'show2'
      get 'edit2'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      patch 'basic_info'
      get 'edit_overwork_notice'
      patch 'update_overwork_notice'
      get '/attendances/edit_one_month_apply'
      patch 'attendances/update_one_month_apply'
      patch 'attendances/request_one_month_application'
      get '/attendances/edit_attendance_apply'
      patch '/attendances/update_attendance_apply'
      get '/attendances/edit_attendance_log'
    end

    resources :attendances do
      collection {post :import}
      member do
        patch 'update'
        get 'edit_overwork_request'
        patch 'update_overwork_request'
      end
    end
  end
  
  resources :attendance_change_approval_log, only: :index
end

app/models/attendance.rb
# == Schema Information
#
# Table name: attendances
#
#  id                              :integer          not null, primary key
#  worked_on                       :date
#  started_at                      :datetime
#  finished_at                     :datetime
#  note                            :string
#  next_day_check                  :boolean
#  user_id                         :integer          not null
#  contents                        :string
#  select_superior_id              :integer
#  superior_state                  :integer
#  modification                    :boolean
#  one_month_superior_id           :integer
#  one_month_status                :integer
#  apply_one_month                 :date
#  finish_time                     :datetime
#  tomorrow                        :boolean
#  renewed_started_at              :datetime
#  renewed_finished_at             :datetime
#  frequent_changes_of_started_at  :datetime
#  frequent_changes_of_finished_at :datetime
#  change_shift                    :boolean
#  change_month                    :boolean
#  description                     :string
#  attendance_state                :integer
#  previous_attendance_state       :integer
#  superior_choice_id              :integer
#  one_month_superior_status       :string
#  overwork_superior_status        :string
#  attendance_superior_status      :string
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#
# Indexes
#
#  index_attendances_on_one_month_superior_id  (one_month_superior_id)
#  index_attendances_on_select_superior_id     (select_superior_id)
#  index_attendances_on_superior_choice_id     (superior_choice_id)
#  index_attendances_on_user_id                (user_id)
#
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :select_superior, class_name: 'User', optional: true
  belongs_to :one_month_superior, class_name: 'User', optional: true
  belongs_to :superior_choice, class_name: 'User', optional: true
  before_validation :set_prev_attendance_state, if: 'self.attendance_state_changed?'
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  validates :finish_time, presence: true, on: :update_overwork_request
  validates :contents, presence: true, length: {minimum: 3}, on: :update_overwork_request
  validates :select_superior_id, presence: true, on: :update_overwork_request
  
  validates :one_month_superior_id, presence: true, on: :request_one_month_application
  

# 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
  validate :renewed_started_at_than_renewed_finished_at_fast_if_invalid

  #validates :modification, inclusion: {in: [true]}

  def started_at_than_finished_at_fast_if_invalid
    #return if tomorrow
    #binding.pry
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at && tomorrow == false
    end
  end
  
  def renewed_started_at_than_renewed_finished_at_fast_if_invalid
    #binding.pry
    #return if tomorrow
    if started_at.present? && finished_at.present? && renewed_started_at.present? && renewed_finished_at.present? && tomorrow == true
      errors.add(:renewed_started_at, "より早い退勤時間は無効です") if renewed_started_at < renewed_finished_at
    elsif started_at.blank? && finished_at.blank? && renewed_started_at.present? && renewed_finished_at.present? && tomorrow == true
      errors.add(:renewed_started_at, "より早い退勤時間は無効です") if renewed_started_at < renewed_finished_at
    elsif started_at.present? && finished_at.present? && renewed_started_at.present? && renewed_finished_at.present? && tomorrow == false
      errors.add(:renewed_started_at, "より早い退勤時間は無効です") if renewed_started_at > renewed_finished_at
    elsif started_at.blank? && finished_at.blank? && renewed_started_at.present? && renewed_finished_at.present? && tomorrow == false
      errors.add(:renewed_started_at, "より早い退勤時間は無効です") if renewed_started_at > renewed_finished_at
    end
  end

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  private
  
  
  def set_prev_attendance_state
    #binding.pry
    unless attendance_state_in_database == 1
     self.previous_attendance_state = attendance_state_in_database
    end
  end
  
  
  
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  before_action :set_user, only:  [:edit_one_month, :update_one_month, :edit_overwork_request, :edit_overwork_notice, :edit_one_month_apply]
  before_action :logged_in_user, only: [:update, :edit_one_month, :edit_overwork_request, :edit_overwork_notice]
  before_action :edit_correct_user, only: [:edit_one_month]
  #before_action :log_correct_user, only: [:edit_attendance_log]
  before_action :set_one_month, only: [:edit_one_month, :update_one_month]

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  
  def index
    @search_params = attendance_search_params
    @users = Attendance.search(@search_params).includes(:month)
  end
  

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  
  def edit_one_month
    #user = User.find(params[:id])
    #first_day = Date.current.beginning_of_month
    #last_day = first_day.end_of_month
    #@attendances = user.attendances.where(worked_on: first_day..last_day).order(:worked_on)
    @attendance_apply = User.where(superior: true).where.not(id: current_user)
    if current_user.admin?
      flash[:danger] = "管理者は閲覧権限がありません。"
    redirect_to root_path
    end
  end
  
  def update_one_month
    @first_day = params[:date]&.to_date || Date.current.beginning_of_month
    @attendance = Attendance.find(params[:id])
    #binding.pry
    ActiveRecord::Base.transaction do # トランザクションを開始します。
    attendances_params.each do |id, item|
      #binding.pry
    #if item[:renewed_started_at] == "" || item[:started_at] == "" && item[:renewed_finished_at] == "" || item[:finished_at] == "" && item[:description] != "" && item[:superior_choice_id] != "" && item[:tomorrow] == true || item[:tomorrow] == false
    if item[:renewed_started_at] == "" && item[:renewed_finished_at] == "" && item[:description] != "" && item[:superior_choice_id] != "" && item[:tomorrow] != ""
      next
    end
     if item[:renewed_started_at].present? && item[:renewed_finished_at].blank?
      flash[:danger] = "出勤時間のみの勤怠変更はできません"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
     end
     if item[:renewed_started_at].blank? && item[:renewed_finished_at].present?
      flash[:danger] = "退勤時間のみの勤怠変更はできません"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
     end
     if item[:renewed_started_at].present? && item[:renewed_finished_at].present? && item[:superior_choice_id] == "" && item[:description] == ""
      flash[:danger] = "備考・指示者確認㊞を入力してください。"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
     end
     if item[:superior_choice_id] != "" && item[:description] != "" && item[:renewed_started_at] == "" && item[:renewed_finished_at] == ""
      flash[:danger] = "出勤時間・退勤時間を入力してください。"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
     end
     if item[:superior_choice_id] != "" && item[:description] != "" && item[:started_at] != "" && item[:finished_at] != "" && item[:renewed_started_at] == "" && item[:renewed_finished_at] == ""
      flash[:danger] = "出勤時間・退勤時間を入力してください。"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
     end
     
     if item[:superior_choice_id].present? && item[:description].blank?
      flash[:danger] = "備考の記載がありません。"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
     end
     if item[:superior_choice_id].blank? && item[:description].present?
      flash[:danger] = "指示者確認㊞が選択されていません。"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
     end
     #if item[:description] == "" && item[:superior_choice_id].present?
      #flash[:danger] = "備考が入力されていない為勤怠変更に失敗しました。"
       #redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
     #end
      if item[:superior_choice_id] == "" && item[:description] != ""
       flash[:danger] = "指示者確認が選択されていない為勤怠変更に失敗しました。"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
      end
      
      if item[:renewed_started_at].present? && item[:renewed_finished_at].blank?
      flash[:danger] = "出勤時間のみの勤怠変更はできません"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
      end
      if item[:renewed_started_at].blank? && item[:renewed_finished_at].present?
      flash[:danger] = "退勤時間のみの勤怠変更はできません"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
      end
      
      #if item[:started_at].present? && item[:finished_at].blank?
      #flash[:danger] = "出勤時間のみの勤怠変更はできません"
       #redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
      #end
      if item[:started_at].blank? && item[:finished_at].present?
      flash[:danger] = "退勤時間のみの勤怠変更はできません"
       redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
      end
      #if item[:renewed_started_at] > item[:renewed_finished_at] && item[:tomorrow] == false
      #flash[:danger] = "出勤時間より早い退勤時間は無効です。"
       #redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
      #end

      attendance = Attendance.find_by(id: id)
      #binding.pry
      if attendance.attendance_state == 2 #承認
        attendance.attributes = item
       if attendance.has_changes_to_save?
         attendance.attendance_state = 1 #申請中
         #attendance.tomorrow = false
         attendance.save!
       end
      else
        attendance.attributes = item
       if attendance.has_changes_to_save?
        attendance.attendance_state = 1
        attendance.save!
       end
      end
      #binding.pry
   end
  end
  flash[:success] = "勤怠変更を申請しました。"
  redirect_to user_url(@user, date: @first_day.strftime("%F"))
  #binding.pry
  rescue ActiveRecord::RecordInvalid  # トランザクションによるエラーの分岐です。
   flash[:danger] = "出勤時間より早い退勤時間は無効です。"
   #binding.pry
   redirect_to attendances_edit_one_month_user_url(date: params[:date]) and return
  end
  
  def edit_overwork_request
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    @current_user = User.find(params[:user_id])
    @over_apply = User.where(superior: true).where.not(id: current_user)
  end
   
   
  def update_overwork_request
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    @attendance.attributes = update_overwork_request_params
    if @attendance.next_day_check == false && @attendance.finish_time.hour < @user.designated_work_end_time.hour
      flash[:danger] = "残業申請に失敗しました。"
      redirect_to user_url(@user, date: @attendance.worked_on&.beginning_of_month.strftime("%F")) and return
    end
    if @attendance.save(context: :update_overwork_request)
      flash[:success] = "残業を申請しました。"
      redirect_to user_url(@user, date: @attendance.worked_on&.beginning_of_month.strftime("%F"))
    else
      #if @attendance.finish_time
      flash[:danger] = "残業申請に失敗しました。"
      redirect_to user_url(@user, date: @attendance.worked_on&.beginning_of_month.strftime("%F"))
    end
  end
  

  def request_one_month_application
    @user = User.find(params[:id])
    @attendance = @user.attendances.find_by(worked_on: params[:date])
    params[:user][:one_month_superior_status] = "申請中"
    @attendance.attributes = request_one_month_application_params
    if @attendance.save(context: :request_one_month_application)
      flash[:success] = "１カ月の勤怠申請しました。"
      redirect_to user_url(@user, date: @attendance.worked_on&.beginning_of_month.strftime("%F"))
    else
      #binding.pry
      flash[:danger] = "１カ月の勤怠申請に失敗しました。"
      redirect_to user_url(@user, date: @attendance.worked_on&.beginning_of_month.strftime("%F"))
    end
    #@attendance.update(request_one_month_application_params)
    #binding.pry
    #flash[:success] = "１カ月の勤怠申請しました。"
    #redirect_to user_url(@user)
  end
  
  def edit_one_month_apply
    #@first_day = Date.current.beginning_of_month
    #@users = User.where.not(id: 1).where.not(id: current_user.id)
    @user = User.find(params[:id])
    @attendances = Attendance.where(one_month_superior_status: '申請中', one_month_status: 1, one_month_superior: @user.id).order(user_id: "ASC", worked_on: 'ASC').group_by(&:user_id)
  end
  
  def update_one_month_apply
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      update_one_month_apply_params.each do |id, item|
        if ActiveRecord::Type::Boolean.new.cast(item[:change_month]) && item[:one_month_status] == "2"
          attendance = Attendance.find(id)
          attendance.update!(one_month_status: item[:one_month_status])
          flash[:success] = "１カ月分勤怠申請の処理を完了しました。"
        end
        if ActiveRecord::Type::Boolean.new.cast(item[:change_month]) && item[:one_month_status] == "1"
          flash[:danger] = "指示者確認㊞ステータスを変更してください。"
        end
        if ActiveRecord::Type::Boolean.new.cast(item[:change_month]) && item[:one_month_status] == "3"
          attendance = Attendance.find(id)
          attendance.update!(one_month_superior_id: nil,  one_month_superior_status: nil, one_month_status: 3)
          flash[:success] = "１カ月分勤怠申請の処理を完了しました。"
        end
        if ActiveRecord::Type::Boolean.new.cast(item[:change_month]) && item[:one_month_status] == "4"
          attendance = Attendance.find(id)

app/helpers/attendances_helper.rb
module AttendancesHelper
  def working_times(start, finish, attendance)
    if attendance.tomorrow
      #format("%.2f", (((renewed_finish - renewed_start) / 60) / 60.to_f * 0.6) + 24)
      format("%.2f", (((finish - start) / 60) / 60.0) + 24)
    else
      #format("%.2f", (((finish - start) / 60) / 60.to_f * 0.6))
      format("%.2f", (((finish - start) / 60) / 60.0))
    end
  end
  
  def renew_working_times(renewed_start, renewed_finish, attendance)
    if attendance.tomorrow
      #format("%.2f", (((renewed_finish - renewed_start) / 60) / 60.to_f * 0.6) + 24)
      format("%.2f", (((renewed_finish - renewed_start) / 60) / 60.0) + 24)
    else
      #format("%.2f", (((renewed_finish - renewed_start) / 60) / 60.to_f * 0.6))
      format("%.2f", (((renewed_finish - renewed_start) / 60) / 60.0))
    end
  end
  
  def checked_working_times(checked_start, checked_finish, attendance)
    if attendance.tomorrow
      format("%.2f", (((checked_finish - checked_start) / 60) / 60.0) + 24)
    else
      format("%.2f", (((checked_finish - checked_start) / 60) / 60.0))
    end
  end
  
  
  def format_min(time)
    format("%.2d", ((time.strftime('%M').to_i / 15).round) * 15)
    #format("%.2d", ((time.strftime('%M').to_i )))
  end
  
  def overtime_info(start_datetime, finish_datetime, attendance)
    if attendance.next_day_check
     #format("%.2f",(finish_datetime.hour - start_datetime.hour) + ((finish_datetime.min - start_datetime.min) / 60.to_f * 0.6) + 24)
     format("%.2f",(finish_datetime.hour - start_datetime.hour) + ((finish_datetime.min - start_datetime.min) / 60.to_f) + 24)
    else
    #binding.pry
     #format("%.2f",(finish_datetime.hour - start_datetime.hour) + ((finish_datetime.min - start_datetime.min) / 60.to_f * 0.6))
     format("%.2f",(finish_datetime.hour - start_datetime.hour) + (finish_datetime.min - start_datetime.min) / 60.to_f)
    end
  end
end

app/views/attendances/_edit_attendance_apply.html.erb
<% provide(:title, "Edit One Month Apply") %>
<% provide(:class_text, 'edit-one-month-apply') %>
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
      <div class="modal-body">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <%= form_with model: @user, url: attendances_update_attendance_apply_user_path(@user, @attendance), local: true, method: :patch do |f| %>
            <% @users.each do |user| %>
              <h3 align="center" class="modal-title"><%= "【 #{user.name}からの勤怠変更申請 】" %></h3>
              <% user.attendances.where(superior_choice: current_user.id).where(attendance_state: 1).order(worked_on: 'ASC').each do |attendance|  %>
               <table class="table table-bordered table-condensed" id="table-attendances">
                  <thead>
                    <tr>
                      <th rowspan="3">日付</th>
                      <th rowspan="3">曜日</th>
                      <th colspan="4">変更前</th>
                      <th colspan="4">変更後</th>
                      <th rowspan="3">備考</th>
                      <th rowspan="3">指示者確認㊞</th>
                      <th rowspan="3">変更</th>
                      <th rowspan="3">勤怠を確認する</th>
                    </tr>
                    <tr>
                      <th colspan="2">出社</th>
                      <th colspan="2">退社</th>
                      <th colspan="2">出社</th>
                      <th colspan="2">退社</th>
                    </tr>
                    <tr>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                      <th>時</th>
                      <th>分</th>
                    </tr>
                  </thead>
                  
                    <%= f.fields_for "attendances[]", attendance do |attendance_field|  %>
                      <tbody>
                        <tr>
                          <td><%= l(attendance.worked_on, format: :short) %></td>
                          <td>
                          <% if attendance.worked_on.wday == 6 %>
                            <font color = "blue">土</font>
                          <% elsif attendance.worked_on.wday == 0 %>
                            <font color = "red">日</font>
                          <% else %>
                            <%= $days_of_the_week[attendance.worked_on.wday] %>
                          <% end %>
                          </td>
                          <td><%= attendance.started_at.hour if attendance.started_at.present? %></td>
                          <td><%= format_min(attendance.started_at) if attendance.started_at.present? %></td>
                          <td><%= attendance.finished_at.hour if attendance.finished_at.present? %></td>
                          <td><%= format_min(attendance.finished_at) if attendance.finished_at.present? %></td>
                          <td><%= attendance.renewed_started_at.hour if attendance.renewed_started_at.present? %></td>
                          <td><%= format_min(attendance.renewed_started_at) if attendance.renewed_started_at.present? %></td>
                          <td><%= attendance.renewed_finished_at.hour if attendance.renewed_finished_at.present? %></td>
                          <td><%= format_min(attendance.renewed_finished_at) if attendance.renewed_finished_at.present? %> </td>
                          <td><%= attendance.description %></td>
                          <td><%= attendance_field.select :attendance_state, {"申請中": 1, "承認": 2, "否認": 3, "なし": 4}, class: "form-control", required: true %></td>
                          <td><%= attendance_field.check_box :change_shift, checked: false %></td>
                          <td><%= link_to "確認", show2_user_path(user, date: attendance.worked_on&.beginning_of_month.strftime("%F")), class: "btn btn-primary" %></td>
                        </tr>
                      </tbody>
                    <% end %>
                </table>
              <% end %>
            <% end %>
            <%= f.submit "変更を送信する", class: "btn btn-block btn-primary" %>
          <% end %>
      </div>
  </div>
</div>

app/views/attendances/_edit_one_month_apply.html.erb
<% provide(:title, "Edit One Month Apply") %>
<% provide(:class_text, 'edit-one-month-apply') %>
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
      <div class="modal-body">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <%= form_with model: @user, url: attendances_update_one_month_apply_user_path(@user), local: true, method: :patch do |f| %>
            <% @attendances.each do |user_id, attendances| %>
              <h3 align="center" class="modal-title">【<%= User.find(user_id).name %>からの１カ月分の勤怠申請】</h3>
              <table class="table table-bordered table-condensed" id="table-attendances">
                  <thead>
                    <tr>
                      <th colspan="3">月</th>
                      <th colspan="3">指示者確認㊞</th>
                      <th colspan="3">変更</th>
                      <th colspan="3">勤怠を確認する</th>
                    </tr>
                  </thead>
                  <% attendances.each do |attendance| %>
                    <%= f.fields_for "attendances[]", attendance do |day|  %>
                      <tbody>
                        <tr>
                          <td colspan="3"><%= attendance.worked_on.month %>月</td>
                          <td colspan="3"><%= day.select :one_month_status, { "申請中":1, "承認":2, "否認":3, "なし":4} , { required: true }, {class: "form-control" } %>
                          <td colspan="3"><%= day.check_box :change_month, {}, "true", "false" %></td>
                          <td colspan="3"><%= link_to "確認", show2_user_path(user_id, date: attendance.worked_on&.beginning_of_month.strftime("%F")), class: "btn btn-primary" %></td>
                        </tr>
                      </tbody>
                      <%# binding.pry %>
                    <% end %>
                  <% end %>
              </table>
            <% end %>
            <%= f.submit "変更を送信する", class: "btn btn-block btn-primary" %>
          <% end %>
      </div>
  </div>
</div>

app/views/attendances/edit_attendance_apply.js.erb
$("#edit-attendance-apply").html("<%= escape_javascript(render 'edit_attendance_apply') %>");
$("#edit-attendance-apply").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @users, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠変更申請</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
         <th rowspan>日付</th>
         <th rowspan>曜日</th>
         <th rowspan>出社</th>
         <th rowspan>退社</th>
         <th rowspan>翌日</th>
         <th rowspan>在社時間</th>
         <th rowspan>備考</th>
         <th rowspan>指示者確認</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |attendance| %>
         <%= f.fields_for "attendances[]", attendance do |attendance_field| %>
            <tr>
              <td rowspan><%= l(attendance.worked_on, format: :short) %></td>
              <td rowspan>
               <% if attendance.worked_on.wday == 6 %>
                <font color="blue">土</font>
               <% elsif attendance.worked_on.wday == 0 %>
                <font color="red">日<font>
               <% else %>
                <%= $days_of_the_week[attendance.worked_on.wday] %></td>
               <% end %>
              </td>
              <% if Date.current <= attendance.worked_on && attendance.finished_at.blank? %>
               <% if attendance.started_at.present? && attendance.finished_at.present? %>
                 <td rowspan><%= attendance_field.time_field :renewed_started_at, class: "form-control", readonly: true %></td>
                 <td rowspan><%= attendance_field.time_field :renewed_finished_at, class: "form-control", readonly: true %></td>
               <% else %>
                 <td rowspan><%= attendance_field.time_field :started_at, class: "form-control", readonly: true %></td>
                 <td rowspan><%= attendance_field.time_field :finished_at, class: "form-control", readonly: true %></td>
               <% end %>
                 <td rowspan></td>
                 <td colsapn>
                <% if attendance.renewed_started_at.present? && attendance.renewed_finished_at.present? %>
                  <%= renew_working_times(attendance.renewed_started_at, attendance.renewed_finished_at) %>
                <% end %>
               </td>
               <td rowspan><%= attendance_field.text_field :description, placeholder: "内容を記入してください", readonly: true, class: "form-control" %></td>
               <td rowspan>
                <%= attendance_field.collection_select :superior_choice_id, @attendance_apply, :id, :name, {:prompt => "選択できません"}, disabled: true %>
               </td>
              <% else %>
               <td rowspan><%= attendance_field.time_field :renewed_started_at, class: "form-control" %></td>
               <td rowspan><%= attendance_field.time_field :renewed_finished_at, class: "form-control" %></td>
               <td rowspan><%= attendance_field.check_box :tomorrow, {}, "true", "false" %></td>
               <td colsapn>
                <% if attendance.started_at.present? && attendance.finished_at.present? && attendance.renewed_started_at.blank? && attendance.renewed_finished_at.blank? %>
                  <%= working_times(attendance.started_at, attendance.finished_at, attendance) %>
                <% end %>
                <% if attendance.renewed_started_at.present? && attendance.renewed_finished_at.present? %>
                  <%= renew_working_times(attendance.renewed_started_at, attendance.renewed_finished_at, attendance) %>
                <% end %>
               </td>
               <td rowspan><%= attendance_field.text_field :description, placeholder: "内容を記入してください", class: "form-control" %></td>
               <td rowspan>
                <%= attendance_field.collection_select :superior_choice_id, @attendance_apply, :id, :name, :prompt => "送信先を選択" %>
               </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/attendances/edit_one_month_apply.js.erb
$("#edit-one-month-apply").html("<%= escape_javascript(render 'edit_one_month_apply') %>");
$("#edit-one-month-apply").modal("show");

app/views/attendances/edit_overwork_request.js.erb
$("#edit-overwork-request").html("<%= escape_javascript(render 'edit_overwork_request') %>");
$("#edit-overwork-request").modal("show");